FROM golang:alpine3.17

WORKDIR /app

COPY . .

RUN go mod download

RUN go install github.com/cosmtrek/air@latest

RUN go install github.com/swaggo/swag/cmd/swag@latest

EXPOSE 8080

CMD [ "air", "-d" ]
