info:
  contact: {}
paths:
  /auth/register:
    post:
      consumes:
      - application/json
      description: Registration endpoint for user new users to register for an account
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Registration
  /health:
    get:
      description: Health Check Endpoint that doesn't require authentication
      responses:
        "200":
          description: Success
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
      summary: Health Check
swagger: "2.0"
